### backend/alembic/versions/410f749d3a6f_add_facility_type_to_facility_model.py
"""add facility_type to facility model

Revision ID: 410f749d3a6f
Revises: 8afd746183f8
Create Date: 2025-10-17 16:04:29.967732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410f749d3a6f'
down_revision: Union[str, Sequence[str], None] = '8afd746183f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    facilitytype_enum = sa.Enum('production', 'office', 'warehouse', 'cold_storage', name='facilitytype')
    facilitytype_enum.create(op.get_bind())
    op.add_column('facilities', sa.Column('facility_type', facilitytype_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'facility_type')
    facilitytype_enum = sa.Enum('production', 'office', 'warehouse', 'cold_storage', name='facilitytype')
    facilitytype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
