### backend/alembic/versions/460f1c01dd32_add_role_to_company_members.py
"""Add role to company members

Revision ID: 460f1c01dd32
Revises: f09bb9c8256b
Create Date: 2025-10-16 21:13:16.482830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460f1c01dd32'
down_revision: Union[str, Sequence[str], None] = 'f09bb9c8256b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'company_members', 
        sa.Column(
            'role', 
            sa.Enum('owner', 'admin', 'data_entry', 'viewer', name='companymemberrole'), 
            nullable=False,
            # YENİ: Mevcut satırlar için varsayılan değeri sunucuya bildir
            server_default=sa.text("'owner'")
        )
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_members', 'role')
    # ### end Alembic commands ###
