### backend/alembic/versions/5df07d82e5f3_add_companyfinancials_model.py
"""Add CompanyFinancials model

Revision ID: 5df07d82e5f3
Revises: 460f1c01dd32
Create Date: 2025-10-17 14:31:32.217183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df07d82e5f3'
down_revision: Union[str, Sequence[str], None] = '460f1c01dd32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financials',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('avg_electricity_cost_kwh', sa.Float(), nullable=True),
    sa.Column('avg_gas_cost_m3', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_financials')
    # ### end Alembic commands ###
