### backend/alembic/versions/745820c20014_add_activitydata_model.py
"""Add ActivityData model

Revision ID: 745820c20014
Revises: 0f2750bb3f1a
Create Date: 2025-10-12 18:36:54.818296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745820c20014'
down_revision: Union[str, Sequence[str], None] = '0f2750bb3f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Enum('electricity', 'natural_gas', 'diesel_fuel', name='activitytype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('calculated_co2e_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_data_id'), 'activity_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_data_id'), table_name='activity_data')
    op.drop_table('activity_data')
    # ### end Alembic commands ###
