### backend/alembic/versions/893f6b859fc6_add_emission_factor_model.py
"""add emission_factor model

Revision ID: 893f6b859fc6
Revises: b47cad8d2eb3
Create Date: 2025-10-17 16:58:57.982243

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '893f6b859fc6'
down_revision: Union[str, Sequence[str], None] = 'b47cad8d2eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_emission_factors_key'), 'emission_factors', ['key'], unique=False)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_index(op.f('ix_emission_factors_key'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
