### backend/alembic/versions/ac3cf1f3800d_add_companyfinancials_model.py
"""Add CompanyFinancials model

Revision ID: ac3cf1f3800d
Revises: 5df07d82e5f3
Create Date: 2025-10-17 14:35:02.140280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3cf1f3800d'
down_revision: Union[str, Sequence[str], None] = '5df07d82e5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
