### backend/alembic/versions/b47cad8d2eb3_add_surface_area_m2_to_facility.py

"""add surface_area_m2 to facility

Revision ID: b47cad8d2eb3
Revises: 410f749d3a6f
Create Date: 2025-10-17 16:17:01.066796

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b47cad8d2eb3'
down_revision: Union[str, Sequence[str], None] = '410f749d3a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('surface_area_m2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'surface_area_m2')
    # ### end Alembic commands ###
