### backend/alembic/versions/c519807e88b7_add_industry_type_to_company.py
"""add industry_type to company

Revision ID: c519807e88b7
Revises: 893f6b859fc6
Create Date: 2025-10-17 17:20:44.815165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c519807e88b7'
down_revision: Union[str, Sequence[str], None] = '893f6b859fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    industry_enum = sa.Enum('manufacturing', 'services', 'retail', 'other', name='industrytype')
    industry_enum.create(op.get_bind())
    
    target_metric_enum = sa.Enum('co2e_reduction_percentage', 'energy_reduction_kwh', name='targetmetrictype')
    target_metric_enum.create(op.get_bind())

    op.add_column('companies', sa.Column('industry_type', industry_enum, nullable=True))

    op.create_table('sustainability_targets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('target_metric', target_metric_enum, nullable=False),
        sa.Column('target_value', sa.Float(), nullable=False),
        sa.Column('target_year', sa.Integer(), nullable=False),
        sa.Column('baseline_year', sa.Integer(), nullable=False),
        sa.Column('baseline_value', sa.Float(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sustainability_targets_id'), 'sustainability_targets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sustainability_targets_id'), table_name='sustainability_targets')
    op.drop_table('sustainability_targets')

    op.drop_column('companies', 'industry_type')
    
    industry_enum = sa.Enum('manufacturing', 'services', 'retail', 'other', name='industrytype')
    industry_enum.drop(op.get_bind())

    target_metric_enum = sa.Enum('co2e_reduction_percentage', 'energy_reduction_kwh', name='targetmetrictype')
    target_metric_enum.drop(op.get_bind())

    op.create_table('suggestion_parameters',
        sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('key', name='suggestion_parameters_pkey')
    )
    # ### end Alembic commands ###
